#configuration of GMP-252 ID=44
carbo_44 = minimalmodbus.Instrument('/dev/ttyUSB0', 44)	
carbo_44.serial.baudrate = 19200 				# BaudRate
carbo_44.serial.bytesize = 8					# Number of data bits to be requested
carbo_44.serial.parity = minimalmodbus.serial.PARITY_NONE	# Parity Setting here is NONE but can be ODD or EVEN
carbo_44.serial.stopbits = 2					# Number of stop bits
carbo_44.mode = minimalmodbus.MODE_RTU				# Mode to be used (RTU or ascii mode)
carbo_44.clear_buffers_before_each_transaction = True
carbo_44.close_port_after_each_call = True